# filebeat.yml

filebeat:
  inputs:
  - type: docker
    containers:
      ids:
      - "*"

#  prospectors:
#  - type: log
#    enabled: true
#    paths:
#    - /usr/share/filebeat/dockerlogs/*/*.log

# for debugging
#output:
#  console:
#    pretty: true

output:
  logstash:
    hosts: ["logstash:5044"]

