version: '3.1'


services:

  # see: https://hub.docker.com/_/postgres/
  database:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: s3cr37
      POSTGRES_USER: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: keycloak
    ports:
    - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: s3cr37
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: s3cr37
      # Uncomment the line below if you want to specify JDBC parameters.
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "ssl=true"
    ports:
    - 8081:8080 # host:container
    depends_on:
    - database


# keycload admin console is at: http://localhost:8081/auth/admin/
# adamin login:  admin/s3cr37
