version: "3.6"

networks:
  user-bridge:
    ipam:
      config:
      - subnet: 172.18.0.0/16

volumes:
  # create persistent volumes
  filebeat-data:
  postgres-data:
  redis-data:
  es-data:

#volumes:
#  postgres_data:
#    driver: local

services:


  # echo "vm.max_map_count=262144" >> /usr/lib/sysctl.d/vm.conf
  #  or
  # sysctl -w vm.max_map_count=262144
  # see: https://github.com/maxyermayank/docker-compose-elasticsearch-kibana/blob/master/docker-compose.yml
  # index, search & aggregation
  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
    - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
    # kibaba endpoint
    - 9200:9200
    - 9300:9300
    volumes:
    - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - es-data:/usr/share/elasticsearch/data
    networks:
      user-bridge:
        ipv4_address: 172.18.0.110
    logging:  # see: https://stackoverflow.com/questions/43486505/docker-compose-json-logging-driver-labels-env
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"


  # kibana UI
  kibana:
    hostname: kibana
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:6.5.0
    ports:
    # UI
    - 5601:5601
    volumes:
    - ./kibana/kibana.yml:/etc/kibana/kibana.yml
    networks:
      user-bridge:
        ipv4_address: 172.18.0.115
    logging:  # see: https://stackoverflow.com/questions/43486505/docker-compose-json-logging-driver-labels-env
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
    - elasticsearch
  # setup in UI: index: logstash-*
  # @timestamp


  logstash:
    hostname: logstash
    container_name: logstash
    build:
      context: ./logstash
      args:
        ELK_VERSION: 6.5.0
    volumes:
    - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
    - 5044:5044
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      user-bridge:
        ipv4_address: 172.18.0.120
    logging:  # see: https://stackoverflow.com/questions/43486505/docker-compose-json-logging-driver-labels-env
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
    - elasticsearch


  #
  #  pickup logfile and send them to logstash
  #
  # see: https://medium.com/@bcoste/powerful-logging-with-docker-filebeat-and-elasticsearch-8ad021aecd87
  filebeat:
    hostname: filebeat
    container_name: filebeat
    build:
      context: ./filebeat
    networks:
      user-bridge:
        ipv4_address: 172.18.0.125
    volumes:
    # needed to persist filebeat tracking data :
    - filebeat-data:/usr/share/filebeat/data:rw
    # needed to access all docker logs on the host (read only) :
    - /var/lib/docker/containers:/usr/share/filebeat/dockerlogs:ro
    # needed to access additional informations about containers
    - /var/run/docker.sock:/var/run/docker.sock
    logging:  # see: https://stackoverflow.com/questions/43486505/docker-compose-json-logging-driver-labels-env
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
    - elasticsearch



  # see: https://hub.docker.com/_/postgres/
  database:
    hostname: database
    container_name: database
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: s3cr37
      POSTGRES_USER: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: keycloak
    ports:
    - 5432:5432
    #depends_on:
    # - filebeat
    # volumes:
    # - postgres_data:/var/lib/postgresql/data
    networks:
      user-bridge:
        ipv4_address: 172.18.0.130



  keycloak:
    hostname: keycloak
    container_name: keycloak
    image: jboss/keycloak:4.7.0.Final
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: s3cr37
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: s3cr37
      # Uncomment the line below if you want to specify JDBC parameters.
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "ssl=true"
    ports:
    - 8081:8080 # host:container
    depends_on:
    - database
     # - filebeat
    networks:
      user-bridge:
        ipv4_address: 172.18.0.135
# keycload admin console is at: http://localhost:8081/auth/admin/
# adamin login:  admin/s3cr37


