
server:
  port: 8080

spring:
  application:
    name: apollo
  datasource:
    url: jdbc:h2:file:${java.io.tmpdir}/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: false
  jpa:
    hibernate:
      ddlAuto: create-drop
    show-sql: false


logging:
  level:
    root: info
